### ISSUE TITLE
Design system: Text input

### ISSUE THREAD

**Issue by wceolin** [zoonk/design#9]
## Tasks

- [x] Text field: Default
- [x] Text field: Hover
- [x] Text Field: Focus
- [x] Text Field: Filled
- [x] Text Field: Error
- [x] Text Field: Helper text
